import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// If no keys, return a mock client that falls back to localStorage
const useLocalFallback = !supabaseUrl || !supabaseAnonKey;

export const supabase = useLocalFallback
  ? null
  : createClient(supabaseUrl, supabaseAnonKey);

/* ── Table schema (run this in Supabase SQL Editor once) ──
create table if not exists wishlists (
  id bigint generated by default as identity primary key,
  email text unique not null,
  product_ids jsonb default '[]'::jsonb,
  marketing_optin boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Note: anon INSERT/UPDATE/DELETE/SELECT policies have been removed.
-- All wishlist access now goes through the Express API (service role).
alter table wishlists enable row level security;
create policy "service can manage wishlists" on wishlists
  for all to service_role using (true) with check (true);
*/

/* ── Wishlist API ── */

export async function getWishlist(email) {
  if (!email) return [];
  if (useLocalFallback) {
    try { return JSON.parse(localStorage.getItem('rw_wishlist') || '[]'); }
    catch { return []; }
  }
  try {
    const r = await fetch('/api/wishlist?email=' + encodeURIComponent(email));
    const d = await r.json();
    const items = Array.isArray(d.items) ? d.items : [];
    return items[0]?.product_ids || [];
  } catch { return []; }
}

export async function saveWishlist(email, productIds, marketingOptin) {
  if (useLocalFallback) {
    localStorage.setItem('rw_wishlist', JSON.stringify(productIds));
    return;
  }
  try {
    await fetch('/api/wishlist', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, product_ids: productIds }),
    });
  } catch {}
}

export async function signupUser(email, marketingOptin) {
  if (useLocalFallback) {
    localStorage.setItem('rw_email', email);
    return;
  }
  // IMPORTANT: Do NOT include product_ids in the upsert — that would reset
  // the user's existing wishlist to empty when a returning user signs in
  // again (e.g. after clearing localStorage). The API preserves existing data.
  await saveWishlist(email, undefined, marketingOptin);
}

/* ── Custom Products API (read-only public; write operations route through server API) ── */

export async function getCustomProducts() {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('custom_products')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) { console.warn('getCustomProducts:', error.message); return []; }
  return data || [];
}

/* ── Admin-only operations (route through server API — HttpOnly cookie handles auth) ── */

export async function addCustomProduct(product) {
  try {
    const r = await fetch('/api/admin/products/add', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(product),
    });
    const d = await r.json();
    return d.data || null;
  } catch { return null; }
}

export async function updateCustomProduct(productId, updates) {
  try {
    const r = await fetch('/api/admin/products/update', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ product_id: productId, ...updates }),
    });
    const d = await r.json();
    if (!r.ok) { console.warn('updateCustomProduct failed:', d); return null; }
    return d.data || true;
  } catch (e) { console.warn('updateCustomProduct error:', e); return null; }
}

export async function deleteCustomProduct(id) {
  try {
    const r = await fetch('/api/admin/products/delete', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id }),
    });
    const d = await r.json();
    return d.ok === true;
  } catch { return false; }
}

export async function uploadProductImage(file, productId) {
  try {
    const b64 = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result;
        const base64 = typeof result === 'string' ? result.split(',')[1] || result : result;
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
    const ext = file.name.split('.').pop() || 'webp';
    const r = await fetch('/api/admin/products/upload-image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ productId, imageBase64: b64, ext }),
    });
    const d = await r.json();
    if (!r.ok) { console.warn('uploadProductImage failed:', d); return null; }
    return d.url || null;
  } catch (e) { console.warn('uploadProductImage error:', e); return null; }
}

/* ── Orders API (admin-only, route through server API) ── */

export async function getOrders() {
  try {
    const r = await fetch('/api/admin/orders');
    const d = await r.json();
    return d.orders || [];
  } catch { return []; }
}

export async function updateOrderStatus(id, status) {
  try {
    await fetch('/api/admin/orders/update-status', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id, status }),
    });
  } catch {}
}
