import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// If no keys, return a mock client that falls back to localStorage
const useLocalFallback = !supabaseUrl || !supabaseAnonKey;

export const supabase = useLocalFallback
  ? null
  : createClient(supabaseUrl, supabaseAnonKey);

/* ── Table schema (run this in Supabase SQL Editor once) ──
create table if not exists wishlists (
  id bigint generated by default as identity primary key,
  email text unique not null,
  product_ids jsonb default '[]'::jsonb,
  marketing_optin boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Allow anonymous read/upsert by email
alter table wishlists enable row level security;
create policy "anon can read by email" on wishlists
  for select to anon using (true);
create policy "anon can upsert by email" on wishlists
  for insert to anon with check (true);
create policy "anon can update by email" on wishlists
  for update to anon using (true);
*/

/* ── Wishlist API ── */

export async function getWishlist(email) {
  if (!email) return [];
  if (useLocalFallback) {
    try { return JSON.parse(localStorage.getItem('rw_wishlist') || '[]'); }
    catch { return []; }
  }
  const { data, error } = await supabase
    .from('wishlists')
    .select('product_ids')
    .eq('email', email)
    .single();
  if (error && error.code !== 'PGRST116') console.warn('Supabase getWishlist:', error.message);
  return data?.product_ids || [];
}

export async function saveWishlist(email, productIds, marketingOptin) {
  if (useLocalFallback) {
    localStorage.setItem('rw_wishlist', JSON.stringify(productIds));
    return;
  }
  const { error } = await supabase
    .from('wishlists')
    .upsert({ email, product_ids: productIds, marketing_optin: marketingOptin ?? false, updated_at: new Date().toISOString() },
      { onConflict: 'email' });
  if (error) console.warn('Supabase setWishlist:', error.message);
}

export async function signupUser(email, marketingOptin) {
  if (useLocalFallback) {
    localStorage.setItem('rw_email', email);
    return;
  }
  // IMPORTANT: Do NOT include product_ids in the upsert — that would reset
  // the user's existing wishlist to empty when a returning user signs in
  // again (e.g. after clearing localStorage). Supabase preserves the
  // existing product_ids when they're omitted, and for new rows the DB
  // default `'[]'::jsonb` is used.
  const { error } = await supabase
    .from('wishlists')
    .upsert({ email, marketing_optin: marketingOptin ?? false, updated_at: new Date().toISOString() },
      { onConflict: 'email' });
  if (error) console.warn('Supabase signup:', error.message);
}

/* ── Custom Products API (read-only public; write operations route through server API) ── */

export async function getCustomProducts() {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('custom_products')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) { console.warn('getCustomProducts:', error.message); return []; }
  return data || [];
}

/* ── Admin-only operations (route through server API with admin token) ── */

function getAdminToken() {
  try {
    return localStorage.getItem('rw_admin_token') || '';
  } catch { return ''; }
}

export async function addCustomProduct(product) {
  const token = getAdminToken();
  if (!token) return null;
  try {
    const r = await fetch('/api/admin/products/add', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': token },
      body: JSON.stringify(product),
    });
    const d = await r.json();
    return d.data || null;
  } catch { return null; }
}

export async function updateCustomProduct(productId, updates) {
  const token = getAdminToken();
  if (!token) return null;
  try {
    const r = await fetch('/api/admin/products/update', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': token },
      body: JSON.stringify({ product_id: productId, ...updates }),
    });
    const d = await r.json();
    return d.data || null;
  } catch { return null; }
}

export async function deleteCustomProduct(id) {
  const token = getAdminToken();
  if (!token) return false;
  try {
    const r = await fetch('/api/admin/products/delete', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': token },
      body: JSON.stringify({ id }),
    });
    const d = await r.json();
    return d.ok === true;
  } catch { return false; }
}

export async function uploadProductImage(file, productId) {
  const token = getAdminToken();
  if (!token) return null;
  try {
    // Convert file to base64 on the client
    const b64 = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result;
        // Strip data: URL prefix if present
        const base64 = typeof result === 'string' ? result.split(',')[1] || result : result;
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
    const ext = file.name.split('.').pop() || 'webp';
    const r = await fetch('/api/admin/products/upload-image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': token },
      body: JSON.stringify({ productId, imageBase64: b64, ext }),
    });
    const d = await r.json();
    return d.url || null;
  } catch { return null; }
}

/* ── Orders API (admin-only, route through server API) ── */

export async function getOrders() {
  const token = getAdminToken();
  if (!token) return [];
  try {
    const r = await fetch('/api/admin/orders', {
      headers: { 'x-admin-token': token },
    });
    const d = await r.json();
    return d.orders || [];
  } catch { return []; }
}

export async function updateOrderStatus(id, status) {
  const token = getAdminToken();
  if (!token) return;
  try {
    await fetch('/api/admin/orders/update-status', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-admin-token': token },
      body: JSON.stringify({ id, status }),
    });
  } catch {}
}
