import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// If no keys, return a mock client that falls back to localStorage
const useLocalFallback = !supabaseUrl || !supabaseAnonKey;

export const supabase = useLocalFallback
  ? null
  : createClient(supabaseUrl, supabaseAnonKey);

/* ── Table schema (run this in Supabase SQL Editor once) ──
create table if not exists wishlists (
  id bigint generated by default as identity primary key,
  email text unique not null,
  product_ids jsonb default '[]'::jsonb,
  marketing_optin boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Allow anonymous read/upsert by email
alter table wishlists enable row level security;
create policy "anon can read by email" on wishlists
  for select to anon using (true);
create policy "anon can upsert by email" on wishlists
  for insert to anon with check (true);
create policy "anon can update by email" on wishlists
  for update to anon using (true);
*/

/* ── Wishlist API ── */

export async function getWishlist(email) {
  if (!email) return [];
  if (useLocalFallback) {
    try { return JSON.parse(localStorage.getItem('rw_wishlist') || '[]'); }
    catch { return []; }
  }
  const { data, error } = await supabase
    .from('wishlists')
    .select('product_ids')
    .eq('email', email)
    .single();
  if (error && error.code !== 'PGRST116') console.warn('Supabase getWishlist:', error.message);
  return data?.product_ids || [];
}

export async function saveWishlist(email, productIds, marketingOptin) {
  if (useLocalFallback) {
    localStorage.setItem('rw_wishlist', JSON.stringify(productIds));
    return;
  }
  const { error } = await supabase
    .from('wishlists')
    .upsert({ email, product_ids: productIds, marketing_optin: marketingOptin ?? false, updated_at: new Date().toISOString() },
      { onConflict: 'email' });
  if (error) console.warn('Supabase setWishlist:', error.message);
}

export async function signupUser(email, marketingOptin) {
  if (useLocalFallback) {
    localStorage.setItem('rw_email', email);
    return;
  }
  const { error } = await supabase
    .from('wishlists')
    .upsert({ email, product_ids: [], marketing_optin: marketingOptin ?? false },
      { onConflict: 'email' });
  if (error) console.warn('Supabase signup:', error.message);
}

/* ── Custom Products API ── */

export async function getCustomProducts() {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('custom_products')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) { console.warn('getCustomProducts:', error.message); return []; }
  return data || [];
}

export async function addCustomProduct(product) {
  if (!supabase) return null;
  const { data, error } = await supabase
    .from('custom_products')
    .insert(product)
    .select()
    .single();
  if (error) { console.warn('addCustomProduct:', error.message); return null; }
  return data;
}

export async function deleteCustomProduct(id) {
  if (!supabase) return false;
  const { error } = await supabase
    .from('custom_products')
    .delete()
    .eq('id', id);
  if (error) { console.warn('deleteCustomProduct:', error.message); return false; }
  return true;
}

export async function uploadProductImage(file, productId) {
  if (!supabase) return null;
  const ext = file.name.split('.').pop() || 'webp';
  const path = `${productId}.${ext}`;
  const { error } = await supabase.storage
    .from('product-images')
    .upload(path, file, { upsert: true });
  if (error) { console.warn('uploadProductImage:', error.message); return null; }
  const { data } = supabase.storage.from('product-images').getPublicUrl(path);
  return data?.publicUrl || null;
}

/* ── Orders API ── */

export async function saveOrder(order) {
  if (!supabase) return null;
  const { data, error } = await supabase.from('orders').insert(order).select().single();
  if (error) { console.warn('saveOrder:', error.message); return null; }
  return data;
}

export async function getOrders() {
  if (!supabase) return [];
  const { data, error } = await supabase.from('orders').select('*').order('created_at', { ascending: false });
  if (error) { console.warn('getOrders:', error.message); return []; }
  return data || [];
}

export async function updateOrderStatus(id, status) {
  if (!supabase) return;
  await supabase.from('orders').update({ status }).eq('id', id);
}
