-- Run this in Supabase SQL Editor

-- 1. Products table
create table if not exists custom_products (
  id bigint generated by default as identity primary key,
  product_id text unique not null,
  name text not null,
  brand text default '',
  cat text not null,
  price numeric not null,
  was numeric,
  stock integer default 1,
  hue integer default 0,
  img text default '',
  note text default '',
  sizes jsonb default '["S","M","L","XL"]'::jsonb,
  created_at timestamp with time zone default now()
);

alter table custom_products enable row level security;
create policy "anon can read custom_products" on custom_products
  for select to anon using (true);
create policy "anon can insert custom_products" on custom_products
  for insert to anon with check (true);
create policy "anon can update custom_products" on custom_products
  for update to anon using (true);
create policy "anon can delete custom_products" on custom_products
  for delete to anon using (true);

-- 2. Storage bucket for product images
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "anon can view product images"
  on storage.objects for select to anon using (bucket_id = 'product-images');
create policy "anon can upload product images"
  on storage.objects for insert to anon with check (bucket_id = 'product-images');
