-- ═══════════════════════════════════════════════════════════════
-- REWIND Referral System — Run in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- 1. Referral codes table
create table if not exists referral_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  email text not null,
  created_at timestamp with time zone default now(),
  used_count integer default 0,
  max_uses integer default 10,
  reward_discount integer default 10,
  reward_type text default 'percent',
  status text default 'active',
  -- Fraud tracking
  created_ip text default '',
  created_user_agent text default '',
  last_updated timestamp with time zone default now()
);

-- 2. Referral redemptions table
create table if not exists referral_redemptions (
  id bigint generated by default as identity primary key,
  code_id bigint references referral_codes(id) on delete cascade,
  referrer_email text not null,
  referee_email text not null,
  order_num text default '',
  reward_earned boolean default false,
  reward_amount decimal default 0,
  status text default 'pending',
  -- Fraud tracking
  referee_ip text default '',
  referee_user_agent text default '',
  referrer_ip text default '',
  same_ip boolean default false,
  flagged_reason text default '',
  created_at timestamp with time zone default now()
);

-- 3. Indexes for fast lookups
create index if not exists idx_referral_codes_email on referral_codes(email);
create index if not exists idx_referral_codes_code on referral_codes(code);
create index if not exists idx_referral_redemptions_referee on referral_redemptions(referee_email);
create index if not exists idx_referral_redemptions_referrer on referral_redemptions(referrer_email);
create index if not exists idx_referral_redemptions_code_id on referral_redemptions(code_id);
create index if not exists idx_referral_redemptions_order on referral_redemptions(order_num);

-- 4. Row level security (public read by code, admin write)
alter table referral_codes enable row level security;
alter table referral_redemptions enable row level security;

create policy "anon can read referral_codes" on referral_codes
  for select to anon using (code = current_setting('request.jwt.claims')::json->>'code' or true);
create policy "anon can insert referral_codes" on referral_codes
  for insert to anon with check (true);
create policy "anon can read referral_redemptions" on referral_redemptions
  for select to anon using (true);
create policy "anon can insert referral_redemptions" on referral_redemptions
  for insert to anon with check (true);
create policy "anon can update referral_redemptions" on referral_redemptions
  for update to anon using (true);

-- 5. Referral coupon codes table (generated rewards for referrers)
create table if not exists referral_rewards (
  id bigint generated by default as identity primary key,
  referrer_email text not null,
  redemption_id bigint references referral_redemptions(id) on delete cascade,
  promo_code text unique not null,
  reward_type text default 'percent',
  reward_value integer default 10,
  status text default 'pending', -- pending, issued, used
  created_at timestamp with time zone default now(),
  expires_at timestamp with time zone default (now() + interval '90 days')
);

create index if not exists idx_referral_rewards_email on referral_rewards(referrer_email);
create index if not exists idx_referral_rewards_promo on referral_rewards(promo_code);

alter table referral_rewards enable row level security;
create policy "anon can read referral_rewards" on referral_rewards
  for select to anon using (true);
create policy "anon can insert referral_rewards" on referral_rewards
  for insert to anon with check (true);
create policy "anon can update referral_rewards" on referral_rewards
  for update to anon using (true);
