-- Run this once in Supabase SQL Editor to fix wishlist 401

-- Ensure table exists
create table if not exists wishlists (
  id bigint generated by default as identity primary key,
  email text unique not null,
  product_ids jsonb default '[]'::jsonb,
  marketing_optin boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
alter table wishlists enable row level security;

-- Drop existing policies first (in case they exist with wrong permissions)
drop policy if exists "anon can read by email" on wishlists;
drop policy if exists "anon can upsert by email" on wishlists;
drop policy if exists "anon can update by email" on wishlists;

-- Create policies with full anon access
create policy "anon can read by email" on wishlists
  for select to anon using (true);

create policy "anon can upsert by email" on wishlists
  for insert to anon with check (true);

create policy "anon can update by email" on wishlists
  for update to anon using (true);

-- Grant necessary permissions to anon role
grant usage on schema public to anon;
grant all on wishlists to anon;
grant usage on all sequences in schema public to anon;
